# Configuración Nixpacks para Railway - Garantizado para deployment
[phases.setup]
# Paquetes del sistema necesarios
nixPkgs = ['python312', 'postgresql', 'gcc', 'pkg-config', 'git']

[phases.install]
# Instalación robusta de dependencias
cmds = [
    'python -m pip install --upgrade pip setuptools wheel',
    'python -m pip install -r requirements.txt --no-cache-dir'
]

[phases.build]
# Fase de construcción con validación
cmds = [
    'python -c "import sys; print(f\\"Python {sys.version}\\")"',
    'python -m py_compile app.py',
    'python -m py_compile railway_deploy.py',
    'python -m py_compile intelligent_master_deploy.py',
    'echo "✅ Build phase completed successfully"'
]

[start]
# Comando de inicio consistente con railway.toml
cmd = 'python app.py'

[variables]
# Variables de entorno para el build
PYTHONPATH = '.'
PYTHONUNBUFFERED = '1'
PYTHONDONTWRITEBYTECODE = '1'
PORT = '8080'