# Configuraci칩n Nixpacks simplificada para Railway - Versi칩n funcional
[phases.setup]
# Solo los paquetes esenciales que garantizan pip
nixPkgs = ['python3', 'python3Packages.pip', 'postgresql', 'gcc']

[phases.install]
# Instalaci칩n simple y directa
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
# Build b치sico sin complicaciones
cmds = [
    'python -c "print(\\"Build OK\\")"'
]

[start]
# Comando de inicio simple
cmd = 'python app.py'

[variables]
# Variables de entorno para el build
PYTHONPATH = '.'
PYTHONUNBUFFERED = '1'
PYTHONDONTWRITEBYTECODE = '1'
PORT = '8080'