[build]
# Especificar builder con fallback a Docker
builder = "NIXPACKS"
# Si Nixpacks falla, Railway usará automáticamente el Dockerfile

[deploy]
# Comando para iniciar la aplicación
startCommand = "python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
# Variables de entorno críticas para Railway
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PORT = "8080"