[build]
# Especificar explícitamente que es un proyecto Python
builder = "NIXPACKS"
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
# Comando para iniciar la aplicación (múltiples opciones)
startCommand = "python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# Variables de entorno críticas para Railway
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# Configuración específica para Railway
[settings]
# Detectar automáticamente el puerto
detectPort = true