-- Migración 002: Crear tabla de contratos de empréstito
-- Fecha: 2025-09-17
-- Descripción: Migración para crear la tabla emp_contratos con relación a emp_procesos

-- Verificar si la tabla ya existe
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'emp_contratos') THEN
        -- Crear tabla de contratos
        EXECUTE '
        CREATE TABLE emp_contratos (
            id_contrato VARCHAR(50) PRIMARY KEY,
            referencia_del_contrato VARCHAR(100) UNIQUE NOT NULL,
            proceso_de_compra VARCHAR(50) NOT NULL,
            proceso_id INTEGER REFERENCES emp_procesos(id) ON DELETE SET NULL,
            nombre_entidad VARCHAR(500) NOT NULL,
            nit_entidad VARCHAR(20) NOT NULL,
            departamento VARCHAR(100),
            ciudad VARCHAR(100),
            localizacion VARCHAR(200),
            orden VARCHAR(50),
            sector VARCHAR(200),
            rama VARCHAR(50),
            entidad_centralizada VARCHAR(50),
            codigo_entidad VARCHAR(20),
            estado_contrato VARCHAR(50) NOT NULL,
            codigo_de_categoria_principal VARCHAR(50),
            descripcion_del_proceso TEXT,
            objeto_del_contrato TEXT NOT NULL,
            tipo_de_contrato VARCHAR(100),
            modalidad_de_contratacion VARCHAR(100),
            justificacion_modalidad VARCHAR(200),
            fecha_de_firma DATE,
            fecha_de_inicio_del_contrato DATE,
            fecha_de_fin_del_contrato DATE,
            duracion_del_contrato VARCHAR(50),
            fecha_inicio_liquidacion DATE,
            fecha_fin_liquidacion DATE,
            documento_proveedor VARCHAR(20),
            tipodocproveedor VARCHAR(50),
            proveedor_adjudicado VARCHAR(500) NOT NULL,
            es_grupo BOOLEAN,
            es_pyme BOOLEAN,
            codigo_proveedor VARCHAR(20),
            nombre_representante_legal VARCHAR(200),
            nacionalidad_representante_legal VARCHAR(10),
            domicilio_representante_legal VARCHAR(200),
            tipo_identificacion_representante_legal VARCHAR(50),
            identificacion_representante_legal VARCHAR(50),
            genero_representante_legal VARCHAR(20),
            valor_del_contrato NUMERIC(15, 2) NOT NULL CHECK (valor_del_contrato >= 0),
            valor_de_pago_adelantado NUMERIC(15, 2) DEFAULT 0 CHECK (valor_de_pago_adelantado >= 0),
            valor_facturado NUMERIC(15, 2) DEFAULT 0 CHECK (valor_facturado >= 0),
            valor_pendiente_de_pago NUMERIC(15, 2) DEFAULT 0 CHECK (valor_pendiente_de_pago >= 0),
            valor_pagado NUMERIC(15, 2) DEFAULT 0 CHECK (valor_pagado >= 0),
            valor_amortizado NUMERIC(15, 2) DEFAULT 0 CHECK (valor_amortizado >= 0),
            valor_pendiente_de_ejecucion NUMERIC(15, 2) DEFAULT 0 CHECK (valor_pendiente_de_ejecucion >= 0),
            presupuesto_general_nacion NUMERIC(15, 2) DEFAULT 0 CHECK (presupuesto_general_nacion >= 0),
            sistema_general_participaciones NUMERIC(15, 2) DEFAULT 0 CHECK (sistema_general_participaciones >= 0),
            sistema_general_regalias NUMERIC(15, 2) DEFAULT 0 CHECK (sistema_general_regalias >= 0),
            recursos_propios_alcaldias NUMERIC(15, 2) DEFAULT 0 CHECK (recursos_propios_alcaldias >= 0),
            recursos_de_credito NUMERIC(15, 2) DEFAULT 0 CHECK (recursos_de_credito >= 0),
            recursos_propios NUMERIC(15, 2) DEFAULT 0 CHECK (recursos_propios >= 0),
            estado_bpin VARCHAR(50),
            anno_bpin VARCHAR(10),
            bpin VARCHAR(20),
            saldo_cdp VARCHAR(50),
            saldo_vigencia VARCHAR(50),
            condiciones_de_entrega VARCHAR(100),
            habilita_pago_adelantado BOOLEAN,
            liquidacion BOOLEAN,
            obligacion_ambiental BOOLEAN,
            obligaciones_postconsumo BOOLEAN,
            reversion BOOLEAN,
            origen_de_los_recursos VARCHAR(50),
            destino_gasto VARCHAR(50),
            el_contrato_puede_ser_prorrogado BOOLEAN,
            fecha_notificacion_prorroga DATE,
            espostconflicto BOOLEAN,
            dias_adicionados VARCHAR(20),
            puntos_del_acuerdo VARCHAR(100),
            pilares_del_acuerdo VARCHAR(100),
            nombre_del_banco VARCHAR(100),
            tipo_de_cuenta VARCHAR(50),
            numero_de_cuenta VARCHAR(50),
            nombre_ordenador_del_gasto VARCHAR(200),
            tipo_documento_ordenador_gasto VARCHAR(50),
            numero_documento_ordenador_gasto VARCHAR(50),
            nombre_supervisor VARCHAR(200),
            tipo_documento_supervisor VARCHAR(50),
            numero_documento_supervisor VARCHAR(50),
            nombre_ordenador_de_pago VARCHAR(200),
            tipo_documento_ordenador_pago VARCHAR(50),
            numero_documento_ordenador_pago VARCHAR(50),
            urlproceso JSONB,
            dataset_source VARCHAR(50),
            search_field VARCHAR(50),
            referencia_buscada VARCHAR(100),
            search_type VARCHAR(50),
            total_campos INTEGER,
            registro_origen JSONB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )';
        
        RAISE NOTICE 'Tabla emp_contratos creada exitosamente';
    ELSE
        RAISE NOTICE 'Tabla emp_contratos ya existe, omitiendo creación';
    END IF;
END
$$;